// --- pretool_write --- PreToolUse handler for Write/Edit/MultiEdit --------------
//
// Enforces:
//   1. Sensitive path DENY -- blocks writes to .ssh, .gnupg, credential files, system dirs
//   2. Sensitive path ADVISORY -- warns on .git/hooks, shell configs, .npmrc
//   3. Zero-trace content -- blocks AI attribution patterns in file content
//
// Fails open on regex errors.
// ------------------------------------------------------------------------------

use crate::common;
use crate::rules;
use regex::Regex;
use std::sync::LazyLock;

static ZERO_TRACE_RE: LazyLock<Option<Regex>> = LazyLock::new(|| {
    let pat = &rules::RULES.zero_trace_content;
    if pat.is_empty() {
        return None;
    }
    Regex::new(pat).ok()
});

static SENSITIVE_DENY: LazyLock<Vec<(Regex, String)>> = LazyLock::new(|| {
    rules::RULES
        .sensitive_deny_pairs
        .iter()
        .filter_map(|(_id, pat, msg, _shadow)| Regex::new(pat).ok().map(|r| (r, msg.clone())))
        .collect()
});

static SENSITIVE_WARN: LazyLock<Vec<(Regex, String)>> = LazyLock::new(|| {
    rules::RULES
        .sensitive_warn_pairs
        .iter()
        .filter_map(|(_id, pat, msg, _shadow)| Regex::new(pat).ok().map(|r| (r, msg.clone())))
        .collect()
});

/// Record token savings from a deny intervention
fn record_deny_savings() {
    let mut state = common::read_session_state();
    state.estimated_tokens_saved += 200;
    state.savings_deny += 1;
    common::write_session_state(&state);
}

/// PreToolUse handler for Write|Edit|MultiEdit -- path hardening + zero-trace
pub fn run(raw: &str) {
    let input = common::parse_input_or_return!(raw);

    let ti = match input.tool_input.as_ref() {
        Some(v) => v,
        None => return,
    };

    // Extract file path
    let file_path = ti
        .get("file_path")
        .or_else(|| ti.get("path"))
        .and_then(|v| v.as_str())
        .unwrap_or("");

    // 1. Sensitive path DENY -- credential dirs, system dirs
    if !file_path.is_empty() {
        for (re, msg) in SENSITIVE_DENY.iter() {
            if re.is_match(file_path) {
                record_deny_savings();
                common::log_structured(
                    "pretool-write",
                    common::LogLevel::Deny,
                    "sensitive-path",
                    &common::truncate(file_path, 60),
                );
                common::add_session_note("deny", &format!("[sensitive-path] {}", common::truncate(file_path, 60)));
                common::deny("PreToolUse", msg);
                return;
            }
        }

        // 2. Sensitive path ADVISORY -- git hooks, shell configs
        for (re, msg) in SENSITIVE_WARN.iter() {
            if re.is_match(file_path) {
                common::log_structured(
                    "pretool-write",
                    common::LogLevel::Advisory,
                    "sensitive-path",
                    &common::truncate(file_path, 60),
                );
                common::allow_with_advisory("PreToolUse", msg);
                return;
            }
        }
    }

    let tool = input.tool_name.as_deref().unwrap_or("Write");

    // Extract content from whichever field is present
    let content = ti
        .get("content")
        .or_else(|| ti.get("new_string"))
        .or_else(|| ti.get("new_str"))
        .or_else(|| ti.get("text"))
        .and_then(|v| v.as_str())
        .unwrap_or("");

    if content.is_empty() {
        return;
    }

    // 2.5. Shell script lint -- run shellcheck on .sh/.bash file content
    if (file_path.ends_with(".sh") || file_path.ends_with(".bash"))
        && let Some(findings) = run_shellcheck(content)
    {
        common::log(
            "pretool-write",
            &format!(
                "shellcheck: {} findings for {}",
                findings.lines().count(),
                common::truncate(file_path, 40)
            ),
        );
        common::allow_with_advisory("PreToolUse", &findings);
        return;
    }

    // 3. Zero-trace check
    let re = match ZERO_TRACE_RE.as_ref() {
        Some(r) => r,
        None => return, // Broken regex -- fail open
    };

    if re.is_match(content) {
        common::log_structured(
            "pretool-write",
            common::LogLevel::Deny,
            "zero-trace",
            &format!("{} {}", tool, common::truncate(file_path, 60)),
        );
        common::add_session_note("deny", &format!("[zero-trace-write] {} {}", tool, common::truncate(file_path, 60)));
        common::deny(
            "PreToolUse",
            "BLOCKED: Do not include attribution markers (author tags, co-author tags, or 'generated by' references) in file content. Remove the attribution text and retry.",
        );
    } else {
        common::log_structured(
            "pretool-write",
            common::LogLevel::Allow,
            "pass",
            &common::truncate(file_path, 60),
        );
    }
}

/// Run shellcheck on content string, return formatted findings or None.
/// Fails open if shellcheck is not installed.
fn run_shellcheck(content: &str) -> Option<String> {
    use crate::common::subprocess;

    let result = subprocess::run_with_stdin(
        "shellcheck",
        &["--shell=bash", "--format=gcc", "-"],
        Some(content.as_bytes()),
    )?;

    // Exit 0 = no issues; non-zero = findings or error
    if result.exit_code == 0 {
        return None;
    }

    let findings = result.stdout;
    if findings.trim().is_empty() {
        return None;
    }

    let total = findings.lines().count();
    let lines: Vec<&str> = findings.lines().take(5).collect();
    let truncated = if total > 5 { " (showing first 5)" } else { "" };

    Some(format!(
        "shellcheck findings{}:\n{}",
        truncated,
        lines.join("\n")
    ))
}
